import marimo

__generated_with = "0.24.0"
app = marimo.App(
    width="medium",
    layout_file="layouts/04_dspy_agent_notebook.slides.json",
)


@app.cell(hide_code=True)
def imports():
    import html
    import json
    import sys
    import time
    from pathlib import Path
    from uuid import uuid4

    import dspy
    import marimo as mo

    project_root = Path(__file__).resolve().parents[1]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    from dspy_factorio.agent import API_HINT, AgentConfig, FactorioProgrammer, build_lm, strip_code_fences
    from dspy_factorio.env import get_environment_info, load_project_env, make_env, obs_text, reset_env, save_render, step_code
    load_project_env()
    return (
        AgentConfig,
        FactorioProgrammer,
        Path,
        build_lm,
        dspy,
        get_environment_info,
        html,
        json,
        make_env,
        mo,
        obs_text,
        project_root,
        reset_env,
        save_render,
        step_code,
        strip_code_fences,
        time,
        uuid4,
    )


@app.cell(hide_code=True)
def introduction(mo):
    mo.md("""
    # Give an AI a world to act in

    **Task = world + goal + starting kit + scoring rule**

    ```text
    goal + inventory
            │
            ▼
    reset → write Python → game.step() → observation + reward
                  ▲                            │
                  └──────── next action ────────┘
    ```

    - **Action:** a short Python program, generated by the model.
    - **Observation:** game output and errors → feedback for the next action.
    - **Reward:** automatic production; the scenario sets the quota.
    - **Images:** our view of the game. The agent reads text.
    """)
    return


@app.cell(hide_code=True)
def explain_loop(FactorioProgrammer, mo):
    _signature_lines = [
        "class FactorioProgrammer(dspy.Signature):",
        '    """Write one short Factorio Python program."""',
        "",
    ]
    for _name, _field in FactorioProgrammer.input_fields.items():
        _signature_lines.append(f"    {_name}: {_field.annotation.__name__} = dspy.InputField()")
    for _name, _field in FactorioProgrammer.output_fields.items():
        _signature_lines.append(f"    {_name}: {_field.annotation.__name__} = dspy.OutputField()")
    mo.vstack([
        mo.md("## DSPy: define the inputs and outputs\n**A Python library for model-based programs.**\n\n- **Signature:** the contract we give the model.\n- **Module:** how we ask it to produce the answer."),
        mo.md("```python\n" + "\n".join(_signature_lines) + "\n```"),
        mo.md("**This is the agent's actual field schema.** `inventory_hint` carries API reminders."),
        mo.accordion({"Full signature instructions": mo.plain_text(FactorioProgrammer.__doc__)}),
    ])
    return


@app.cell(hide_code=True)
def module_factory(FactorioProgrammer, dspy, mo):
    def make_demo_agent(module_name: str) -> dspy.Module:
        if module_name == "ChainOfThought":
            return dspy.ChainOfThought(
                FactorioProgrammer,
                rationale_field=dspy.OutputField(
                    desc="Brief action rationale: what the latest observation implies, "
                         "what you will do next, and what game evidence to check."
                ),
            )
        return dspy.Predict(FactorioProgrammer)

    mo.md("""
    ## Same signature, two modules

    ```python
    agent = dspy.Predict(FactorioProgrammer)
    agent = dspy.ChainOfThought(FactorioProgrammer)
    ```

    - **Predict:** returns `program`.
    - **ChainOfThought:** returns `reasoning` + `program`.
    - Only `program` runs in Factorio. Check the rationale against game output.
    """)
    return (make_demo_agent,)


@app.cell(hide_code=True)
def scenario_catalog_cell(get_environment_info):
    from dspy_factorio.env import list_envs

    scenario_catalog = {
        name: get_environment_info(name)
        for name in list_envs(throughput_only=True)
        if (get_environment_info(name) or {}).get("num_agents", 1) == 1
    }
    _preferred = ["iron_ore_throughput", "iron_plate_throughput", "iron_gear_wheel_throughput", "electronic_circuit_throughput"]
    scenario_options = {
        name.replace("_throughput", "").replace("_", " ").capitalize(): name
        for name in [*_preferred, *sorted(set(scenario_catalog) - set(_preferred))]
        if name in scenario_catalog
    }
    return scenario_catalog, scenario_options


@app.cell(hide_code=True)
def controls(mo, scenario_options):
    model_picker = mo.ui.dropdown(
        ["openai/gpt-4o-mini", "openai/gpt-5.1", "Custom model"],
        value="openai/gpt-4o-mini", label="Model", full_width=True,
    )
    custom_model = mo.ui.text(placeholder="provider/model", label="Custom model ID", full_width=True)
    module_picker = mo.ui.dropdown(["Predict", "ChainOfThought"], value="Predict", label="DSPy module")
    scenario_picker = mo.ui.dropdown(scenario_options, value="Iron ore", searchable=True, label="Scenario", full_width=True)
    step_budget = mo.ui.slider(1, 10, value=4, step=1, label="Agent steps", show_value=True)
    run_episode = mo.ui.run_button(label="Run new episode · reset game", kind="success", full_width=True)
    mo.vstack([
        mo.md("## Change the task, keep the program"),
        mo.hstack([model_picker, module_picker], widths="equal"),
        custom_model,
        mo.hstack([scenario_picker, step_budget], widths="equal"),
        run_episode,
        mo.md("- Select a **scenario**, **model**, and **module** → **Run new episode**.\n- Every run resets the selected world. Changing settings alone does nothing.\n- Compare runs below; a step limit is not a success verdict."),
        mo.accordion({"Before presenting": mo.md("Cluster running · provider keys in `.env` · one game controller. Keep **On cell change → autorun** enabled. Use marimo interrupt to stop. Optional spectator: `127.0.0.1:34197`.")}),
    ])
    return (
        custom_model,
        model_picker,
        module_picker,
        run_episode,
        scenario_picker,
        step_budget,
    )


@app.cell(hide_code=True)
def task(mo, scenario_catalog, scenario_picker):
    env_id = scenario_picker.value
    environment_description = scenario_catalog[env_id]["description"]
    bootstrap = "print(inspect_inventory())\nprint(get_entities())"
    scenario_api_hint = (
        "Use FLE enums Resource.* and Prototype.*; select resources and machines for the goal. "
        "nearest(Resource.X) locates a resource; move_to(position) before distant placement. "
        "place_entity(entity=Prototype.X, position=position, direction=Direction.NORTH). "
        "Use inspect_inventory(), get_entities(), insert_item(item, entity, quantity=n), "
        "and connect_entities(source, target, connection_type=Prototype.TransportBelt). "
        "Print evidence, inspect existing machines, and fix errors from the last observation."
    )
    mo.vstack([
        mo.md("**Selected goal**"),
        mo.plain_text(environment_description),
        mo.md("- Goal and scoring come from the scenario registry.\n- Same signature, module, and loop for every scenario.\n- Startup only inspects inventory and entities; the model chooses what to build."),
    ])
    return bootstrap, env_id, environment_description, scenario_api_hint


@app.cell(hide_code=True)
def history_state(mo):
    get_episodes, set_episodes = mo.state([])
    return get_episodes, set_episodes


@app.cell(hide_code=True)
def render_helpers(Path, html, mo):
    def text_panel(text: str) -> mo.Html:
        return mo.Html(
            '<pre style="white-space:pre-wrap;overflow-wrap:anywhere;max-height:340px;'
            'overflow:auto;font-size:13px;padding:12px;border:1px solid var(--gray-5);'
            'border-radius:8px">' + html.escape(text) + '</pre>'
        )


    def step_card(record: dict) -> mo.Html:
        details = [mo.md(f"**{record['label']}**")]
        if record.get("reasoning"):
            details.extend([mo.md("**Model rationale · ChainOfThought**"), text_panel(record["reasoning"])])
        if record.get("program"):
            details.extend([mo.md("**Generated program**" if record["index"] > 0 else "**Scripted bootstrap**"), text_panel(record["program"])])
        details.extend([mo.md("**Game response**"), text_panel(record["observation"])])
        if record.get("reward") is not None:
            details.append(mo.md(f"Reward: **{record['reward']}** · Environment done: **{record['done']}**"))
        if record.get("image"):
            return mo.hstack([
                mo.vstack(details),
                mo.image(Path(record["image"]), alt=record["label"], width="100%", caption="Game state after this step"),
            ], widths="equal", align="start")
        return mo.vstack(details)

    return step_card, text_panel


@app.cell(hide_code=True)
def camera(Path, save_render):
    from dspy_factorio.env import namespace
    from fle.env import Position

    def save_episode_image(env, path: Path, *, follow_factory: bool = True) -> Path:
        """Follow placed machines in any scenario, otherwise follow the player."""
        entities = namespace(env).get_entities() if follow_factory else []
        machines = [entity for entity in entities if entity.name not in {"character", "item-on-ground"}]
        if machines:
            center = Position(
                x=sum(entity.position.x for entity in machines) / len(machines),
                y=sum(entity.position.y for entity in machines) / len(machines),
            )
            spread = max(max(abs(entity.position.x - center.x), abs(entity.position.y - center.y)) for entity in machines)
            return save_render(env, path, mode="simple", position=center, zoom=min(2.0, 16 / (spread + 8)))
        return save_render(env, path, mode="simple", zoom=0.25)

    return (save_episode_image,)


@app.cell(hide_code=True)
def episode_loop(
    AgentConfig,
    bootstrap,
    build_lm,
    custom_model,
    dspy,
    env_id,
    environment_description,
    json,
    make_demo_agent,
    make_env,
    mo,
    model_picker,
    module_picker,
    obs_text,
    project_root,
    reset_env,
    run_episode,
    save_episode_image,
    scenario_api_hint,
    set_episodes,
    step_budget,
    step_card,
    step_code,
    strip_code_fences,
    text_panel,
    time,
    uuid4,
):
    mo.stop(not run_episode.value, mo.md("Ready when you are. Select a model and click **Run new episode**."))
    _model = custom_model.value.strip() if model_picker.value == "Custom model" else model_picker.value
    mo.stop(not _model or "/" not in _model, mo.callout("Enter a model ID such as provider/model.", kind="warn"))
    _goal = environment_description
    _started = time.monotonic()
    _episode_id = time.strftime("%Y%m%d_%H%M%S") + "_" + uuid4().hex[:8]
    _out = project_root / ".fle" / "renders" / "meetup" / _episode_id
    _out.mkdir(parents=True, exist_ok=True)
    _episode = {
        "id": _episode_id, "model": _model, "module": module_picker.value,
        "scenario": env_id, "goal": _goal, "budget": step_budget.value, "steps": [], "status": "running",
        "elapsed": 0.0, "directory": str(_out),
    }
    _env = None
    mo.output.replace(mo.md(f"**Connecting to Factorio…** · {_model} · {module_picker.value}"))
    try:
        _agent = make_demo_agent(module_picker.value)
        _lm = build_lm(AgentConfig(model=_model)).copy(cache=False, num_retries=0, timeout=45)
        _env = make_env(env_id, run_idx=0)
        reset_env(_env)
        _reset_image = save_episode_image(_env, _out / "reset.png", follow_factory=False)
        mo.output.append(mo.image(_reset_image, width=500, caption="Reset map · before the scripted bootstrap"))
        _episode["reset_image"] = str(_reset_image)
        _obs, _reward, _terminated, _truncated, _ = step_code(_env, bootstrap)
        _observation = obs_text(_obs) or "(empty observation)"
        _image = save_episode_image(_env, _out / "step_00.png", follow_factory=False)
        _record = {"index": 0, "label": "Bootstrap · inventory and existing machines", "program": bootstrap,
                   "reasoning": "", "observation": _observation, "image": str(_image),
                   "reward": float(_reward), "done": bool(_terminated or _truncated)}
        _episode["steps"].append(_record)
        mo.output.append(step_card(_record))

        with dspy.context(lm=_lm):
            for _step in range(1, int(step_budget.value) + 1):
                if _terminated or _truncated:
                    break
                mo.output.append(mo.md(f"**Step {_step}/{step_budget.value} · asking {_model}…**"))
                _prediction = _agent(goal=_goal, observation=_observation, inventory_hint=scenario_api_hint)
                _program = strip_code_fences(_prediction.program)
                _reasoning = getattr(_prediction, "reasoning", "") or ""
                _record = {"index": _step, "label": f"Agent step {_step}", "program": _program,
                           "reasoning": _reasoning, "observation": "Execution pending", "image": "",
                           "reward": None, "done": False}
                _episode["steps"].append(_record)
                if _reasoning:
                    mo.output.append(mo.vstack([mo.md("**Model rationale · before execution**"), text_panel(_reasoning)]))
                mo.output.append(text_panel(_program))
                _obs, _reward, _terminated, _truncated, _ = step_code(_env, _program)
                _observation = obs_text(_obs) or "(empty observation)"
                _record.update(observation=_observation, reward=float(_reward), done=bool(_terminated or _truncated))
                _image = save_episode_image(_env, _out / f"step_{_step:02d}.png")
                _record["image"] = str(_image)
                mo.output.append(step_card(_record))
        _episode["status"] = "environment done" if _terminated or _truncated else "step budget reached"
    except KeyboardInterrupt:
        _episode["status"] = "interrupted"
    except Exception as _error:
        # Notebook boundary: keep completed steps visible when a provider or game call fails.
        _episode["status"] = "error"
        _episode["error"] = f"{type(_error).__name__}: {_error}"
    finally:
        if _env is not None:
            try:
                _env.close()
            except Exception as _close_error:
                _episode["cleanup_error"] = f"{type(_close_error).__name__}: {_close_error}"
        _episode["elapsed"] = round(time.monotonic() - _started, 1)
        (_out / "episode.json").write_text(json.dumps(_episode, indent=2), encoding="utf-8")
        set_episodes(lambda previous: [*previous, _episode])

    mo.output.replace(mo.callout(
        f"Episode saved · {_episode['status']} · {_episode['elapsed']} seconds. Review its steps below.",
        kind="warn" if _episode["status"] in ("error", "interrupted") else "info",
    ))
    return


@app.cell(hide_code=True)
def episode_selector(get_episodes, mo):
    _runs = get_episodes()
    _options = {
        f"{_i + 1} · {_r['module']} · {_r['model']} · {_r['elapsed']}s": _r["id"]
        for _i, _r in enumerate(_runs)
    } or {"No episodes yet": None}
    review_episode = mo.ui.dropdown(
        _options, value=list(_options)[-1], disabled=not _runs,
        label="Review episode", full_width=True,
    )
    _summary = [mo.md("## Compare episodes")]
    if _runs:
        _summary.append(mo.ui.table([
            {"Episode": _i + 1, "Scenario": _r.get("scenario", "iron_ore_throughput"), "Module": _r["module"], "Model": _r["model"],
             "Agent steps": sum(_s["index"] > 0 for _s in _r["steps"]),
             "Seconds": _r["elapsed"], "Stop reason": _r["status"]}
            for _i, _r in enumerate(_runs)
        ], selection=None, show_column_summaries=False, show_data_types=False))
    else:
        _summary.append(mo.md("Your runs will appear here. Changing settings does not erase completed episodes."))
    _summary.append(review_episode)
    mo.vstack(_summary)
    return (review_episode,)


@app.cell(hide_code=True)
def episode_review(
    Path,
    get_episodes,
    json,
    mo,
    review_episode,
    step_card,
    text_panel,
):
    mo.stop(review_episode.value is None)
    _selected = next(_r for _r in get_episodes() if _r["id"] == review_episode.value)
    _review = [mo.md(f"**{_selected['module']} · {_selected['model']}**"), mo.plain_text(_selected["goal"])]
    if _selected.get("error"):
        _review.append(mo.callout(text_panel(_selected["error"]), kind="danger"))
    if _selected.get("cleanup_error"):
        _review.append(mo.callout(text_panel(_selected["cleanup_error"]), kind="warn"))
    if _selected.get("reset_image"):
        _review.append(mo.accordion({"Reset map": mo.image(Path(_selected["reset_image"]), width=600)}))
    _review.extend(step_card(_s) for _s in _selected["steps"])
    _review.extend([
        mo.md("**Check:** game response · reward · environment done. A rationale is not proof of success."),
        mo.download(data=json.dumps(_selected, indent=2).encode(), filename=f"{_selected['id']}.json", label="Download episode transcript"),
        mo.plain_text("Saved images and transcript: " + _selected["directory"]),
    ])
    mo.vstack(_review, gap=2)
    return


if __name__ == "__main__":
    app.run()
